name: shashty_app
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  http: ^0.12.0+2
  shared_preferences: ^0.5.3+1
  auto_size_text: ^2.0.1
  url_launcher: ^5.0.3
  mvc_pattern: ^3.3.6
  async: ^2.1.0
  image_picker: ^0.6.0+9
  eva_icons_flutter: ^1.0.4
  fluttertoast: ^3.1.0
  dio: ^2.1.7
  share: ^0.6.1
  flutter_facebook_login: ^2.0.1
  google_sign_in: ^4.0.2
  carousel_slider: ^1.3.0
  carousel_pro: ^0.0.13
  connectivity: ^0.4.3+4
  font_awesome_flutter: ^8.4.0
  lazy_load_scrollview: ^1.0.1
  smooth_star_rating: 1.0.3
  bordered_text: ^0.1.4
  onesignal_flutter: ^2.1.0
  bubble_tab_indicator: ^0.1.4
  datetime_picker_formfield: 0.1.8
  intl: ^0.15.8
  configurable_expansion_tile: ^1.0.0
  firebase_database: ^3.0.5
  flutter_calendar_carousel: ^1.3.18
  flutter_staggered_grid_view: ^0.3.0
  transformer_page_view: ^0.1.6



flutter:
  uses-material-design: true


  assets:
    - assets/
    - assets/imgs/
    - assets/fonts/

  fonts:
    - family: GE_SS
      fonts:
        - asset: assets/fonts/GE_SS_Two_Light.otf
        - asset: assets/fonts/GESSTwoLight-Light.ttf
    - family: Aref Regular
      fonts:
        - asset: assets/fonts/aref-regular.ttf

